# services:
  # mongo:
  #     image: mongo:8
  #     container_name: db
  #     ports:
  #       - "27017:27017"
  #     volumes:
  #       - ./data:/data/db

version: "3.9"
services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: api
    ports:
      - "8080:8080"
      - "6060:6060"
    volumes:
      - ./:/app
    environment:
      - GOFLAGS=-buildvcs=false
