

# services:
  # mongo:
  #     image: mongo:8
  #     container_name: db
  #     ports:
  #       - "27017:27017"
  #     volumes:
  #       - ./data:/data/db

version: "3.9"
services:
  web:
    build: .
    container_name: web_api
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    # environment:
    #   - GOPROXY=direct  # Ensures Go modules are downloaded directly
    #   - GOSUMDB=off      # Disables checksum verification to prevent network failures
    dns:
      - 8.8.8.8
      - 8.8.4.4


