# services:
  # mongo:
  #     image: mongo:8
  #     container_name: db
  #     ports:
  #       - "27017:27017"
  #     volumes:
  #       - ./data:/data/db

version: "3.9"
services:
  api:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: api
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:6060:6060"
    volumes:
      - ./:/app
    environment:
      - GOFLAGS=-buildvcs=false
  ui: 
    image: node:20-alpine
    container_name: ui
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: npm start
    depends_on:
      - api